version: "3"

services:      
  blockchain-indexer:
    build: .
    image: blockchain-indexer
    command: yarn start
    environment:
      - MQ_URL=amqp://host.docker.internal
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/indexer
      - LOG_LEVEL=info
      - NODE_ENV=production
    volumes:
      - .:/usr/src/indexer
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: on-failure