version: "3"

services:
  blockchain-api:
    build: .
    image: blockchain-api
    command: yarn start
    ports:
      - "80:3000"
    environment:
      - MQ_URL=amqp://host.docker.internal
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/indexer
      - LOG_LEVEL=info
    volumes:
      - .:/usr/src/indexer
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: on-failure